Develop
MihailKrasnogorskiy/java-explore-with-me pull request #1
Opened 2022-10-09 16:56 UTC by MihailKrasnogorskiy

2022-10-11 18:54 UTC, EvgenyKoptubenko commented on README.md
> +
В таких огромных проектах в документации должно быть описание как запустить локально проект. Желательно еще иметь скрипт, который собирает и запускает проект.

2022-10-11 19:50 UTC, EvgenyKoptubenko commented on ewm-service/src/main/java/ru/yandex/practicum/service/model/Event.java
> +@Data
Во всех сущностях нужно избегать аннотаций @Data

2022-10-11 19:53 UTC, EvgenyKoptubenko requested changes
Замечаний практически нет. Код сделан очень хорошо и проект просто гигантский. 
Есть предложение не использовать `@Data` для сущностей и так же написать скрипт, который бы запускал локально проект.

2022-10-12 06:22 UTC, MihailKrasnogorskiy commented on README.md
> +
Дополнил.

2022-10-12 06:22 UTC, MihailKrasnogorskiy commented on ewm-service/src/main/java/ru/yandex/practicum/service/model/Event.java
> +@Data
Спасибо, исправил.

2022-10-12 08:32 UTC, EvgenyKoptubenko approved these changes
Работа сделана хорошо. Спасибо. На будущее, например, когда будут спрашивать на собеседовании, то в проекте еще должно быть:
* 		Healthcheck (отдельный эндпоинт, который возвращает данные о том как себя чувствует приложение) - например описать как работает Spring Actuator
* 		На основе Healthcheck можно делать мониторинг, который будет периодически дергать этот эндпоинт и если что-то в healthcheck сломалось, то присылает алерты
* 		Так же в проекте должна быть документация, которая автоматически собирается - Docsify, например
* 		Так что должно быть отдельное приложение, которое собирает проект, создает артифакт и складывает его в хранилище. В Github тоже можно такое сделать.
* 		Во время код ревью должен подключаться Sonar для проверок.
* 		Во время пул реквеста так же должно подсчитываться покрытие кода тестами
* 		Приложение должно быть защищено, т.е. неавторизованные пользователи не должны иметь доступ к эндпоинтам. Почитай про OAUTH2
* 		В пул реквестах должно быть настроено минимальное количество апруверов, которые должны проверить и заапрувить пул реквест перед тем как его можно мерджить
* 		Все должно быть покрыто юнит тестами, так же должны быть написаны BDD тесты.
* 		Все, что не дает коду пройти в прод называется Quality Gates. К таким quality gates можно причислить: jUnit tests, BDD tests, Sonar, Pull Requests checks, code coverage, Catchpoint tests, Performance tests, Browserstack tests.
* 		Так же в приложении должен быть код, который создает инфраструктуру. Например, если ты хостишься в Amazon, то через Terraform нужно создать инфру.
* 		Дополнительный мониториг бизнес фич. У тебя должны быть графики о том как дела у приложения и у клиентов. И так же настроены алерты, если что-то пошло не так.

2022-10-12 15:58 UTC, merged